services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASENAME}
    ports:
      - "5432:5432"