services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      - JVM_OPTS=-Dcassandra.skip_schema_check=true
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml