services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_START_RPC=true
      - CASSANDRA_NUM_TOKENS=1
      - JVM_OPTS=-Dcassandra.skip_schema_check=true
    networks:
      - cassandra_net
    ports:
      - "9042:9042"
    healthcheck:  
      test: ["CMD", "nodetool", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./cassandra/cassandra1.yaml:/etc/cassandra/cassandra.yaml


  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_START_RPC=true
      - CASSANDRA_NUM_TOKENS=1
      - JVM_OPTS=-Dcassandra.skip_schema_check=true
    networks:
      - cassandra_net
    depends_on:
      cassandra1:
        condition: service_healthy
    volumes:
      - ./cassandra/cassandra2.yaml:/etc/cassandra/cassandra.yaml


  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_START_RPC=true
      - CASSANDRA_NUM_TOKENS=1
      - JVM_OPTS=-Dcassandra.skip_schema_check=true
    networks:
      - cassandra_net
    depends_on:
      cassandra1:
        condition: service_healthy
    volumes:
      - ./cassandra/cassandra3.yaml:/etc/cassandra/cassandra.yaml


networks:
  cassandra_net:
    driver: bridge
