services:
  hz1:
    image: "hazelcast/hazelcast:5.4.0"
    container_name: hz-1
    ports:
    - "5701:5701"
    environment:
      - JAVA_OPTS=-Xmx3g -Xms3g
    networks:
      - hz-net

  hz2:
    image: "hazelcast/hazelcast:5.4.0"
    container_name: hz-2
    ports:
    - "5702:5701"
    environment:
      - JAVA_OPTS=-Xmx3g -Xms3g
    networks:
      - hz-net

  hz3:
    image: "hazelcast/hazelcast:5.4.0"
    container_name: hz-3
    ports:
    - "5703:5701"
    environment:
      - JAVA_OPTS=-Xmx3g -Xms3g
    networks:
      - hz-net

networks:
  hz-net: