services:
  hzcp1:
    image: "hazelcast/hazelcast:5.4.0"
    container_name: hz-cp-1
    ports:
    - "5704:5701"
    environment:
      - JAVA_OPTS=-Xmx3g -Xms3g
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/hazelcast.yaml
    volumes:
      - ./hazelcast.yml:/opt/hazelcast/hazelcast.yaml
    networks:
      - hz-cp-net

  hzcp2:
    image: "hazelcast/hazelcast:5.4.0"
    container_name: hz-cp-2
    ports:
    - "5705:5701"
    environment:
      - JAVA_OPTS=-Xmx3g -Xms3g
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/hazelcast.yaml
    volumes:
      - ./hazelcast.yml:/opt/hazelcast/hazelcast.yaml
    networks:
      - hz-cp-net

  hzcp3:
    image: "hazelcast/hazelcast:5.4.0"
    container_name: hz-cp-3
    ports:
    - "5706:5701"
    environment:
      - JAVA_OPTS=-Xmx3g -Xms3g
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/hazelcast.yaml
    volumes:
      - ./hazelcast.yml:/opt/hazelcast/hazelcast.yaml
    networks:
      - hz-cp-net

networks:
  hz-cp-net: